# Generated by Django 3.2.18 on 2023-04-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('localization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('established', models.DateField()),
                ('stadium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('shirt_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match_round', models.IntegerField()),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='main.team')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='main.team')),
                ('stadium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Gol'), ('FOUL', 'Faul'), ('YCAR', 'Żółta kartka'), ('RCAR', 'Czerwona kartka'), ('PENL', 'Karny'), ('GPEN', 'Gol z karnego'), ('OFFS', 'Spalony'), ('CRNR', 'Rożny'), ('FKCK', 'Wolny')], max_length=4)),
                ('minute', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('in_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in', to='main.player')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('out_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_out', to='main.player')),
            ],
        ),
    ]
