# Generated by Django 3.2.18 on 2023-04-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='in_player_id',
            new_name='in_player',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='out_player_id',
            new_name='out_player',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='stadium_id',
            new_name='stadium',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='stadium_id',
            new_name='stadium',
        ),
    ]
