# Generated by Django 4.2.1 on 2023-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230425_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Gk'), ('LB', 'Lb'), ('CB', 'Cb'), ('RB', 'Rb'), ('LM', 'Lm'), ('RM', 'Rm'), ('CM', 'Cm'), ('LS', 'Ls'), ('RS', 'Rs'), ('CS', 'Cs'), ('SUB', 'Sub')], default='SUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Gol'), ('SHOT', 'Strzał'), ('FOUL', 'Faul'), ('YCAR', 'Żółta kartka'), ('RCAR', 'Czerwona kartka'), ('PENL', 'Karny'), ('GPEN', 'Gol z karnego'), ('OFFS', 'Spalony'), ('CRNR', 'Rożny'), ('FKCK', 'Wolny')], max_length=4),
        ),
    ]
