# Generated by Django 4.2.1 on 2023-05-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_position_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favourite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Gol'), ('SHOT', 'Strzał'), ('FOUL', 'Faul'), ('YCAR', 'Żółta kartka'), ('RCAR', 'Czerwona kartka'), ('PENL', 'Karny'), ('GPEN', 'Gol z karnego'), ('OFFS', 'Spalony'), ('CRNR', 'Rożny'), ('FKCK', 'Wolny'), ('ASST', 'Asysta')], max_length=4),
        ),
    ]
