# Generated by Django 4.2.1 on 2023-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_favourite_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Bramkarz'), ('LB', 'Lewy obrońca'), ('CB', 'Środkowy obrońca'), ('RB', 'Prawy obrońca'), ('LM', 'Lewy pomocnik'), ('RM', 'Prawy pomocnik'), ('CM', 'Środkowy pomocnik'), ('LS', 'Lewy napastnik'), ('RS', 'Prawy napastnik'), ('CS', 'Środkowy napastnik'), ('SUB', 'Rezerwowy')], default='SUB', max_length=3),
        ),
    ]
